language: node_js
node_js:
  - node

cache: yarn

install:
  - yarn install

script:
  - yarn build
  - yarn test

deploy:
  provider: firebase
  project: default
  skip_cleanup: true
  on:
    branch: master
  token:
    secure: VM1IIor4RCzpq77Kerw0vUhfufpWznoKVdVWH6hxy2DzQ6US4oFVzudQInN43qi5GTx+OSLVOWiYZsbTghteI3aAqwno2EQHOUWB103M02329R33jDoFwMOacQFDpMZ5FRHIxiTyXAeVWZW8l1IG6x/li68vbHOtkNDP4eUIq45qKC4g40e5WaAJzQVLo1bmgcwOJpl+ucta0e3swu730tr2S+Sl4+FShPJA0651lpP1y432gjyiR7qnaOo8zW15wkZ8ChI7eP+mNiBH5ktfl8XLdI7R42f5CrvpCrltvzUQJ4LI/eUQxKIGx9ruNGhpgNNGPfyesouIFjQMxxJXk0m9Sol9V84ormUFA8e/Csrv9WYT2C1fkMq5tARxr0pXnUhqFc82YsD6Cs1EJ9i3Ljxlb2fdqEJCpUOkgujMm7JY6o6v4lU9yvcdv52ZBZdwhN81KpWvoyL1DX2Ls+HOC7z5BHQ8eKuJ0whn92zkXAWkRXJhiFkIK/wpJ612fhmSpzr+vT8BHvOIly5hU4LP7OK4V/56zEHPeA5UswEmrY9Rq73wRkOYZKv1w7KLnnAKqTnGYsf3FA3G/rxNyYbHTGC8G8NI4UCQqC9I1IZIyXGDW5+pJxh2yXsofhf8mS87yg2GWdBx2OK62sIjyeexPw6OIycx77VjmeiLp6pZfWU=
